-- TODO maybe one day move to google protobuf + translator on client
module Nox.Network.Events where

data Event = Event00
           | Event01
           | Event02
           | Event03
           | Event04
           | Event05
           | Event06 -- TODO: was handled but by literal '6' i think
           | Event07
           | Event08
           | Event09
           | PlayerDisconnect
           | Event0b
           | PingServer
           | PongClient
           | PlayerConnect
           | Event0f
           | Event10
           | Event11
           | Event12
           | Event13
           | Event14
           | Event15
           | Event16
           | Event17
           | Event18
           | Event19
           | Event1a
           | Event1b
           | Event1c
           | Event1d
           | Event1e
           | PlayerJoin
           | Event20
           | Event21
           | Event22
           | Event23
           | Event24
           | Event25
           | Event26
	   | PartialTimestamp
	   | FullTimestamp
	   | NeedTimestamp
	   | SimulatedTimestamp
	   | UseMap
	   | JoinData
	   | NewPlayer
	   | PlayerQuit
	   | SimpleObj
	   | ComplexObj
	   | DestroyObject
	   | ObjectOutOfSight
	   | ObjectInShadows
	   | ObjectFriendAdd
	   | ObjectFriendRemove
	   | ResetFriends
	   | EnableObject
	   | DisableObject
	   | DrawFrame
	   | DestroyWall
	   | OpenWall
	   | CloseWall
	   | ChangeOrAddWallMagic
	   | RemoveWallMagic
	   | PlayerInput
	   | PlayerSetWaypoint
	   | ReportHealth
	   | ReportHealthDelta
	   | ReportPlayerHealth
	   | ReportItemHealth
	   | ReportMana
	   | ReportPoison
	   | ReportStamina
	   | ReportStats
	   | ReportArmorValue
	   | ReportGold
	   | ReportPickup
	   | ReportModifiablePickup
	   | ReportDrop
	   | ReportLesson
	   | ReportMundaneArmorEquip
	   | ReportMundaneWeaponEquip
	   | ReportModifiableWeaponEquip
	   | ReportModifiableArmorEquip
	   | ReportArmorDequip
	   | ReportWeaponDequip
	   | ReportTreasureCount
	   | ReportFlagBallWinner
	   | ReportFlagWinner
	   | ReportDeathmatchWinner
	   | ReportDeathmatchTeamWinner
	   | ReportEnchantment
	   | ReportItemEnchantment
	   | ReportLightColor
	   | ReportLightIntensity
	   | ReportZPlus
	   | ReportZMinus
	   | ReportEquip
	   | ReportDequip
	   | ReportAcquireSpell
	   | ReportTarget
	   | ReportCharges
	   | ReportXStatus
	   | ReportPlayerStatus
	   | ReportModifier
	   | ReportStatModifier
	   | ReportNpc
	   | ReportClientStatus
	   | ReportAnimationFrame
	   | ReportAcquireCreature
	   | ReportLoseCreature
	   | ReportExperience
	   | ReportSpellAward
	   | ReportSpellStart
	   | ReportInventoryLoaded
	   | TryDrop
	   | TryGet
	   | TryUse
	   | TryEquip
	   | TryDequip
	   | TryTarget
	   | TryCreatureEvent
	   | TrySpell
	   | TryAbility
	   | TryCollide
	   | FxParticlefx
	   | FxPlasma
	   | FxSummon
	   | FxSummonCancel
	   | FxShield
	   | FxBlueSparks
	   | FxYellowSparks
	   | FxCyanSparks
	   | FxVioletSparks
	   | FxExplosion
	   | FxLesserExplosion
	   | FxCounterspellExplosion
	   | FxThinExplosion
	   | FxTeleport
	   | FxSmokeBlast
	   | FxDamagePoof
	   | FxLightning
	   | FxEnergyBolt
	   | FxChainLightningBolt
	   | FxDrainMana
	   | FxCharm
	   | FxGreaterHeal
	   | FxMagic
	   | FxSparkExplosion
	   | FxDeathRay
	   | FxSentryRay
	   | FxRicochet
	   | FxJiggle
	   | FxGreenBolt
	   | FxGreenExplosion
	   | FxWhiteFlash
	   | FxGeneratingMap
	   | FxAssemblingMap
	   | FxPopulatingMap
	   | FxDurationSpell
	   | FxDeltazSpellStart
	   | FxTurnUndead
	   | FxArrowTrap
	   | FxVampirism
	   | FxManaBombCancel
	   | UpdateStream
	   | NewAlias
	   | AudioEvent
	   | AudioPlayerEvent
	   | TextMessage
	   | Inform
	   | Important
	   | ImportantAck
	   | Mouse
	   | IncomingClient
	   | OutgoingClient
	   | GameSettings
	   | GameSettings2
	   | UpdateGuiGameSettings
	   | DoorAngle
	   | ObeliskCharge
	   | PentagramActivate
	   | ClientPredictLinear
	   | RequestMap
	   | CancelMap
	   | MapSendStart
	   | MapSendPacket
	   | MapSendAbort
	   | ServerCmd
	   | SysopPw
	   | SysopResult
	   | KeepAlive
	   | ReceivedMap
	   | ClientReady
	   | RequestSavePlayer
	   | XferMsg
	   | PlayerObj
	   | TeamMsg
	   | KickNotification
	   | TimeoutNotification
	   | ServerQuit
	   | ServerQuitAck
	   | Trade
	   | ChatKill
	   | MessagesKill
	   | SeqImportant
	   | ReportAbilityAward
	   | ReportAbilityState
	   | ReportActiveAbilities
	   | Dialog
	   | ReportGuideAward
	   | InterestingId
	   | TimerStatus
	   | RequestTimerStatus
	   | JournalMsg
	   | ChapterEnd
	   | ReportAllLatency
	   | ReportFlagStatus
	   | ReportBallStatus
	   | ReportObjectPoison
	   | ReportMonitorCreature
	   | ReportUnmonitorCreature
	   | ReportTotalHealth
	   | ReportTotalMana
	   | ReportSpellStat
	   | ReportSecondaryWeapon
	   | ReportLastQuiver
	   | InfoBookData
	   | Social
	   | FadeBegin
	   | MusicEvent
	   | MusicPushEvent
	   | MusicPopEvent
	   | PlayerDied
	   | PlayerRespawn
	   | ForgetDrawables
	   | ResetAbilities
	   | RateChange
	   | ReportCreatureCmd
	   | Vote
	   | StatMultipliers
	   | Gauntlet
	   | InventoryFail
           deriving (Eq, Show, Enum)
