-- TODO maybe one day move to google protobuf + translator on client
module Nox.Network.WireProtocol where

import Data.Word (Word8(..))

-- TODO these must be auto-parseable, preferably using Control.Alternative format like in Aeson parser?
data PacketHeader = PacketHeader {
        player  :: Word8
      , unk     :: Word8
      , command :: Word8
} deriving (Eq, Show)

data Command = Command00
             | Command01
             | Command02
             | Command03
             | Command04
             | Command05
             | Command06 -- TODO: was handled
             | Command07
             | Command08
             | Command09
             | PlayerDisconnect -- was unnamed
             | Command0b
             | PingServer
             | Command0d
             | PlayerConnect -- was unnamed
             | Command0f
             | Command10
             | Command11
             | Command12
             | Command13
             | Command14
             | Command15
             | Command16
             | Command17
             | Command18
             | Command19
             | Command1a
             | Command1b
             | Command1c
             | Command1d
             | Command1e
             | PlayerJoin
             | Command20
             | Command21
             | Command22
             | Command23
             | Command24
             | Command25
             | Command26
	     | PartialTimestamp
	     | FullTimestamp
	     | NeedTimestamp
	     | SimulatedTimestamp
	     | UseMap
	     | JoinData
	     | NewPlayer
	     | PlayerQuit
	     | SimpleObj
	     | ComplexObj
	     | DestroyObject
	     | ObjectOutOfSight
	     | ObjectInShadows
	     | ObjectFriendAdd
	     | ObjectFriendRemove
	     | ResetFriends
	     | EnableObject
	     | DisableObject
	     | DrawFrame
	     | DestroyWall
	     | OpenWall
	     | CloseWall
	     | ChangeOrAddWallMagic
	     | RemoveWallMagic
	     | PlayerInput
	     | PlayerSetWaypoint
	     | ReportHealth
	     | ReportHealthDelta
	     | ReportPlayerHealth
	     | ReportItemHealth
	     | ReportMana
	     | ReportPoison
	     | ReportStamina
	     | ReportStats
	     | ReportArmorValue
	     | ReportGold
	     | ReportPickup
	     | ReportModifiablePickup
	     | ReportDrop
	     | ReportLesson
	     | ReportMundaneArmorEquip
	     | ReportMundaneWeaponEquip
	     | ReportModifiableWeaponEquip
	     | ReportModifiableArmorEquip
	     | ReportArmorDequip
	     | ReportWeaponDequip
	     | ReportTreasureCount
	     | ReportFlagBallWinner
	     | ReportFlagWinner
	     | ReportDeathmatchWinner
	     | ReportDeathmatchTeamWinner
	     | ReportEnchantment
	     | ReportItemEnchantment
	     | ReportLightColor
	     | ReportLightIntensity
	     | ReportZPlus
	     | ReportZMinus
	     | ReportEquip
	     | ReportDequip
	     | ReportAcquireSpell
	     | ReportTarget
	     | ReportCharges
	     | ReportXStatus
	     | ReportPlayerStatus
	     | ReportModifier
	     | ReportStatModifier
	     | ReportNpc
	     | ReportClientStatus
	     | ReportAnimationFrame
	     | ReportAcquireCreature
	     | ReportLoseCreature
	     | ReportExperience
	     | ReportSpellAward
	     | ReportSpellStart
	     | ReportInventoryLoaded
	     | TryDrop
	     | TryGet
	     | TryUse
	     | TryEquip
	     | TryDequip
	     | TryTarget
	     | TryCreatureCommand
	     | TrySpell
	     | TryAbility
	     | TryCollide
	     | FxParticlefx
	     | FxPlasma
	     | FxSummon
	     | FxSummonCancel
	     | FxShield
	     | FxBlueSparks
	     | FxYellowSparks
	     | FxCyanSparks
	     | FxVioletSparks
	     | FxExplosion
	     | FxLesserExplosion
	     | FxCounterspellExplosion
	     | FxThinExplosion
	     | FxTeleport
	     | FxSmokeBlast
	     | FxDamagePoof
	     | FxLightning
	     | FxEnergyBolt
	     | FxChainLightningBolt
	     | FxDrainMana
	     | FxCharm
	     | FxGreaterHeal
	     | FxMagic
	     | FxSparkExplosion
	     | FxDeathRay
	     | FxSentryRay
	     | FxRicochet
	     | FxJiggle
	     | FxGreenBolt
	     | FxGreenExplosion
	     | FxWhiteFlash
	     | FxGeneratingMap
	     | FxAssemblingMap
	     | FxPopulatingMap
	     | FxDurationSpell
	     | FxDeltazSpellStart
	     | FxTurnUndead
	     | FxArrowTrap
	     | FxVampirism
	     | FxManaBombCancel
	     | UpdateStream
	     | NewAlias
	     | AudioEvent
	     | AudioPlayerEvent
	     | TextMessage
	     | Inform
	     | Important
	     | ImportantAck
	     | Mouse
	     | IncomingClient
	     | OutgoingClient
	     | GameSettings
	     | GameSettings2
	     | UpdateGuiGameSettings
	     | DoorAngle
	     | ObeliskCharge
	     | PentagramActivate
	     | ClientPredictLinear
	     | RequestMap
	     | CancelMap
	     | MapSendStart
	     | MapSendPacket
	     | MapSendAbort
	     | ServerCmd
	     | SysopPw
	     | SysopResult
	     | KeepAlive
	     | ReceivedMap
	     | ClientReady
	     | RequestSavePlayer
	     | XferMsg
	     | PlayerObj
	     | TeamMsg
	     | KickNotification
	     | TimeoutNotification
	     | ServerQuit
	     | ServerQuitAck
	     | Trade
	     | ChatKill
	     | MessagesKill
	     | SeqImportant
	     | ReportAbilityAward
	     | ReportAbilityState
	     | ReportActiveAbilities
	     | Dialog
	     | ReportGuideAward
	     | InterestingId
	     | TimerStatus
	     | RequestTimerStatus
	     | JournalMsg
	     | ChapterEnd
	     | ReportAllLatency
	     | ReportFlagStatus
	     | ReportBallStatus
	     | ReportObjectPoison
	     | ReportMonitorCreature
	     | ReportUnmonitorCreature
	     | ReportTotalHealth
	     | ReportTotalMana
	     | ReportSpellStat
	     | ReportSecondaryWeapon
	     | ReportLastQuiver
	     | InfoBookData
	     | Social
	     | FadeBegin
	     | MusicEvent
	     | MusicPushEvent
	     | MusicPopEvent
	     | PlayerDied
	     | PlayerRespawn
	     | ForgetDrawables
	     | ResetAbilities
	     | RateChange
	     | ReportCreatureCmd
	     | Vote
	     | StatMultipliers
	     | Gauntlet
	     | InventoryFail
             deriving (Eq, Show, Enum)
